FROM openjdk:11.0-jre-slim
WORKDIR /app
ARG IEX_PUBLIC_KEY
ARG IEX_PRIVATE_KEY
ENV SERVER_PORT=8811
ENV IEX_PUBLIC_KEY=$IEX_PUBLIC_KEY
ENV IEX_PRIVATE_KEY=$IEX_PRIVATE_KEY
COPY /target/stockapp.jar /app/
CMD ["java", "-jar", "stockapp.jar"]